services:
  neko-rooms:
    image: m1k1o/neko-rooms:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      TZ: America/Los_Angeles

      NEKO_ROOMS_MUX: "true"
      NEKO_ROOMS_EPR: 59000-59049
      NEKO_ROOMS_NAT1TO1: ${PUBLIC_IP}
      NEKO_ROOMS_INSTANCE_URL: ${NEKO_ROOMS_PUBLIC_URL}/
      NEKO_ROOMS_INSTANCE_NETWORK: neko-rooms_default
      NEKO_ROOMS_TRAEFIK_ENABLED: "false"
      NEKO_ROOMS_PATH_PREFIX: /room/

      NEKO_ROOMS_MOUNTS_WHITELIST: /opt/neko-rooms/data
      NEKO_ROOMS_STORAGE_ENABLED: "true"
      NEKO_ROOMS_STORAGE_EXTERNAL: /opt/neko-rooms/data
      NEKO_ROOMS_STORAGE_INTERNAL: /data

      NEKO_ROOMS_NEKO_IMAGES: "ghcr.io/m1k1o/neko/firefox:latest sebat2004/neko-firefox-xprintidle:latest"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/neko-rooms/data:/data
      - /opt/neko-rooms/data:/opt/neko-rooms/data